@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION
:START
IF "%1" == "" (
SET /P PATHFINDER="ENTER .EXE FILE PATH: "
IF EXIST "!PATHFINDER!" (
ECHO WinDeployQt is working...
C:\QT\5.13.2\MINGW73_64\BIN\WINDEPLOYQT.EXE --quick "!PATHFINDER!"
) ELSE (
SET /P REPEAT="ERROR! NO FILE INPUT! REPEAT? (Y/N)" 
IF "!REPEAT!" == "Y" (
GOTO START
)
)
) ELSE (
ECHO WinDeployQt is working...
C:\QT\5.13.2\MINGW73_64\BIN\WINDEPLOYQT.EXE --quick "%1"
)
PAUSE